CREATE DATABASE adverts;

CREATE TABLE IF NOT EXISTS country
(
	id_country TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	PRIMARY KEY(id_country)
);

CREATE TABLE IF NOT EXISTS region
(
	id_region TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	id_country TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_region),
	FOREIGN KEY(id_country)
	REFERENCES country(id_country)
);


CREATE TABLE IF NOT EXISTS user
(
	id_user SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL,
	surname VARCHAR(45) NOT NULL,
	login VARCHAR(200) NOT NULL UNIQUE,
	password VARCHAR(200) NOT NULL UNIQUE,
	path_to_photo VARCHAR(45),
	register_date INT UNSIGNED NOT NULL,
	is_admin BOOLEAN NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(45) NOT NULL,
	id_region TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_user),
	FOREIGN KEY(id_region)
	REFERENCES region(id_region)
);

CREATE TABLE IF NOT EXISTS category
(
	id_cat SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	PRIMARY KEY(id_cat)
);

CREATE TABLE IF NOT EXISTS subcategory
(
	id_scat SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	id_cat SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_scat),
	FOREIGN KEY(id_cat)
	REFERENCES category(id_cat)
);

CREATE TABLE IF NOT EXISTS currency
(
	id_cur SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	abbreviation VARCHAR(45) NOT NULL UNIQUE,
	PRIMARY KEY(id_cur)
);

CREATE TABLE IF NOT EXISTS marker
(
	id_m SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	PRIMARY KEY(id_m)
);

CREATE TABLE IF NOT EXISTS price
(
	id_p MEDIUMINT UNSIGNED NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	id_cur SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_p),
	FOREIGN KEY(id_cur)
	REFERENCES currency(id_cur)
);

CREATE TABLE IF NOT EXISTS tag
(
	id_tag MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL UNIQUE,
	PRIMARY KEY(id_tag)
);

CREATE TABLE IF NOT EXISTS advert
(
	id_ad MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(60) NOT NULL,
	description TEXT NOT NULL,
	path_to_photo VARCHAR(45),
	add_time INT UNSIGNED NOT NULL,
	views SMALLINT UNSIGNED NOT NULL,
	id_user SMALLINT UNSIGNED NOT NULL,
	id_scat SMALLINT UNSIGNED NOT NULL,
	id_p MEDIUMINT UNSIGNED,
	id_m SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_ad),
	FOREIGN KEY(id_user)
	REFERENCES user(id_user),
	FOREIGN KEY(id_scat)
	REFERENCES subcategory(id_scat),
	FOREIGN KEY(id_p)
	REFERENCES price(id_p)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(id_m)
	REFERENCES marker(id_m)
);

CREATE TABLE IF NOT EXISTS advert_tag
(
	id_ad MEDIUMINT UNSIGNED NOT NULL,
	id_tag MEDIUMINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_ad, id_tag)
);

CREATE TABLE IF NOT EXISTS favourite
(
	id_user SMALLINT UNSIGNED NOT NULL,
	id_ad MEDIUMINT UNSIGNED NOT NULL,
	PRIMARY KEY(id_user, id_ad)
);

CREATE TABLE IF NOT EXISTS comments
(
	id_comm INT  UNSIGNED NOT NULL AUTO_INCREMENT,
	id_user SMALLINT UNSIGNED NOT NULL,
	id_ad MEDIUMINT UNSIGNED NOT NULL,
	add_time INT UNSIGNED NOT NULL,
	comment TEXT  NOT NULL,
	PRIMARY KEY(id_comm)
);